name: Test Report

on:
  workflow_run:
    workflows: ["Test & Build"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: junit-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit-report.xml
          comment_mode: always
          check_name: Test Results
